### ISSUE TITLE
[BUG] Tabstopp in example breaks linebreak output

### ISSUE THREAD

**Issue by LightSnowDev** [BRIKEV/express-jsdoc-swagger#111]
**Describe the bug**
If your have the tabstopp character in your example json, it breaks the output, resulting in wrong line breaks.

**To Reproduce**
Copy this code into your javascript. Note, that the spaces before the json are tabstopps, not whitespaces.
<pre><code>/**
 * GET /server/healthcheck
 *
 * @summary Returns information the healthiness of the server.
 *
 * @return {object} 200 - success response - application/json
 * @example response - 200 - success response example
 *　{　
 *　　"status": 200,
 *　　"message": "healty"
 *　}
 */
</code></pre>

**Expected behavior**
<img src="https://user-images.githubusercontent.com/10366675/99651269-a6dd3100-2a56-11eb-9127-2ee90963de4d.png" height="400" />

**Screenshots of the error**
<img src="https://user-images.githubusercontent.com/10366675/99651143-86ad7200-2a56-11eb-89dc-827b4f05c5a9.png" height="400" />

**Desktop**
 - OS: Windows 20H2, Node 15.2.1
 - Version: express-jsdoc-swagger 1.1.3

**Additional context**
The issue does not happen with whitespaces. It also does not happen in swagger directly (using a yaml file)

**Comment by kevinccbsg** [comment]
Hi @LightSnowDev,

I copied this code and it does not work because of the tabstops. This is because `JSON.parse` method seems to fail with those characters.

<img width="593" alt="Screenshot 2020-11-29 at 23 55 36" src="https://user-images.githubusercontent.com/12685053/100555824-65daed00-329e-11eb-92cb-8247196eb975.png">

If I use spaces or tabs I don't get the error.

<img width="310" alt="Screenshot 2020-11-29 at 23 56 43" src="https://user-images.githubusercontent.com/12685053/100555845-8d31ba00-329e-11eb-9da4-ffbca36e6807.png">

We tried some different options like parsing the value using `JSON.strinfigy` but that does not solve the problem as it will display as a string and won't be formatted in the Swagger UI as a JSON.

If you work with Tabs and Spaces in VSCode it shows something like this.

<img width="299" alt="Screenshot 2020-11-30 at 00 01 51" src="https://user-images.githubusercontent.com/12685053/100556003-7a6bb500-329f-11eb-8e73-78d939ef45be.png">
<img width="322" alt="Screenshot 2020-11-30 at 00 02 34" src="https://user-images.githubusercontent.com/12685053/100556004-7d66a580-329f-11eb-9080-9928de8efe81.png">

But if we use your code it will show like this. 

<img width="266" alt="Screenshot 2020-11-30 at 00 01 45" src="https://user-images.githubusercontent.com/12685053/100556018-8b1c2b00-329f-11eb-9356-54e7d8c03e4e.png">

It looks different and then our `JSON.parse` as I said before fails. 

I think we could conclude that we should **only use Tabs or spaces** for the examples.

Please if you find I workaround or a solution for tabstops, you could let us know and we will be glad to try it in our code 👍
