### ISSUE TITLE
How to use $ref 

### ISSUE THREAD

**Issue by jwpegram** [BRIKEV/express-jsdoc-swagger#129]
Is there a way to utilize $ref references to other files when using 

```/**
 * Album
 * @typedef {object} Album
 * @property {string} title - The title
 * @property {array<number>} years
 */

**Comment by kevinccbsg** [comment]
Hi @jwpegram in order to use ["$ref](https://swagger.io/docs/specification/using-ref/) you can use the way we define [components](https://brikev.github.io/express-jsdoc-swagger-docs/#/components). You don't need to specify the file you only need to put the right name.

For example

```
/**
 * A song
 * @typedef {object} Song
 * @property {string} title.required - The title
 * @property {string} artist - The artist
 * @property {number} year - The year - double
 */

/**
 * Author model
 * @typedef {object} Author
 * @property {string} name.required - Author name
 * @property {integer} age - Author age - int64
 */

/**
 * Album
 * @typedef {object} Album
 * @property {Song} firstSong
 * @property {Author} author
 */
```

This package will do the "$ref" for you so you don't need to worry about that. In case you want to place the comments in different files. In the configuration, you can specify [multiple files](https://brikev.github.io/express-jsdoc-swagger-docs/#/configuration?id=filespattern).

You can have a look at our [Docs page](https://brikev.github.io/express-jsdoc-swagger-docs/#/) 👍 We have more info, and examples of the possibilities this library offer 😄 

- [Basic example](https://brikev.github.io/express-jsdoc-swagger-docs/#/README?id=usage)
- [Configuration](https://brikev.github.io/express-jsdoc-swagger-docs/#/configuration?id=configuration)
- [Components/schema/$ref](https://brikev.github.io/express-jsdoc-swagger-docs/#/components)
- [Responses](https://brikev.github.io/express-jsdoc-swagger-docs/#/responses)
- [Combine schemas](https://brikev.github.io/express-jsdoc-swagger-docs/#/combineSchemas)
