### ISSUE TITLE
[Feature Request] Infer string type from object (for example Date)

### ISSUE THREAD

**Issue by lachieh** [BRIKEV/express-jsdoc-swagger#166]
At the moment, using the built-in Date object as a type for a property results in an error in the Swagger UI:

```js

/**
 * Product
 * @typedef {object} Product
 * @property {string} description description
 * @property {number} price price in USD cents
 * @property {Date} createdAt created date/time
 * @property {Date} updatedAt updated date/time
 */

/**
 * GET /api/v1/products
 * @summary Get all products
 * @tags Products
 * @returns {Array<Product>} 200 - success response - application/json
 */
```
```
Resolver error at paths./api/v1/products.get.responses.200.content.application/json.schema.items.properties.publishedAt.$ref
Could not resolve reference: #/components/schemas/Date
```

It would be awesome if built-ins like the `Date` object were detected and converted to a `string{date-time}` with a type of [``](https://swagger.io/docs/specification/data-models/data-types/#format)

**Comment by kevinccbsg** [comment]
Hi @lachieh,

Thanks for reporting this! I was reviewing Swagger Docs and the Date object is represented as a `string` with a format.

<img width="777" alt="Screenshot 2021-07-19 at 23 54 37" src="https://user-images.githubusercontent.com/12685053/126232441-ccaf0ff2-0f0d-4f65-a03d-53f7c7a4eda0.png">

The solution for your problem is this one:

```js
/**
 * A song
 * @typedef {object} Song
 * @property {string} title.required - The title
 * @property {string} artist - The artist
 * @property {integer} year - The year - int64
 * @property {string} createdAt - created - date
 */
```

This will look like this:

<img width="1228" alt="Screenshot 2021-07-19 at 23 56 28" src="https://user-images.githubusercontent.com/12685053/126232591-d6b2b42d-ca37-42b4-8f8c-2cf7f8aaed7e.png">

It is showing that date because I selected the `date` type. But you can select all of these types.

<img width="774" alt="Screenshot 2021-07-19 at 23 57 25" src="https://user-images.githubusercontent.com/12685053/126232677-8eac4f45-c5cc-4325-b1a9-e8fde61ec7e7.png">

In our comments, we normally use this format.

```
* @property {TYPE} KEY - DECRIPTION - FORMAT
```

About this

> It would be awesome if built-ins like the Date object were detected and converted to a string{date-time} with a type of ``

You can do that as I mentioned before 👍 

We don't have plans to Infer that type, because we already have that option.

**Comment by lachieh** [comment]
Thanks for taking the time to write a detailed response. I knew about the string formats, but part of the reason I like this library over `swagger-jsdoc` is because it avoids duplication of documentation.

If we were to use the format you suggest, it actually breaks compatibility with jsdoc. In type hints for other files and documentation, I would have to use a separate `@typedef` for the returned type of a function versus the api schemas.

I'm happy to work on this feature, but not if a PR will not be considered.
