### ISSUE TITLE
[BUG] DELETE missing param details

### ISSUE THREAD

**Issue by nakedgremlin** [BRIKEV/express-jsdoc-swagger#176]
**Describe the bug**
It seems like DELETE does not convey the param set in the documentation.

**To Reproduce**

The object and endpoint documentation:

```
/**
 * Logout format to send
 * @typedef {object} Logout
 * @property {string} token.required - Access token for user
 */

/**
 * DELETE /logout
 * @summary Log user out of the system
 * @param {Logout} request.body.required - User access and refresh token
 * /
```

**Expected behavior**
The above should show the params field with the request.body detail, but it only shows an empty area.

Changing DELETE to POST brings up the correct expected view.

This currently only happens with DELETE. All other GET and POST behave as expected with the same settings above.

**Desktop:**
 - OS: OSX
 - Version 10.14.6

**Additional context**

Using the following on a TypeScript code base:
- "express-jsdoc-swagger": "^1.6.3",
- "swagger-ui-express": "^4.1.6"

**Comment by LonelyPrincess** [comment]
I've looked into this and it seems that the library was considering `DELETE` method as an invalid candidate to have a request body. Because of this, your request body definition in the docs for endpoints of that request type was being ignored on purpose.

I've double checked that it's actually possible for `DELETE` requests to include a request body in the [latests specifications](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE), so we'll change this behaviour for the next release. I'll try submitting a PR to fix this either today or tomorrow. 

Thanks for your report!

**Comment by nakedgremlin** [comment]
Thank you @LonelyPrincess 
Looking forward to seeing this in the main release!

**Comment by kevinccbsg** [comment]
@nakedgremlin today we will run a release, we have to include another change for that release 👍

**Comment by kevinccbsg** [comment]
Release Done with this issue fix https://github.com/BRIKEV/express-jsdoc-swagger/releases/tag/v1.6.4
