### ISSUE TITLE
[Enhancement] Refactor process swagger

### ISSUE THREAD

**Issue by kevinccbsg** [BRIKEV/express-jsdoc-swagger#74]
**Is your feature request related to a problem? Please describe.**
We found that we can improve the way we parse our tags to be more performant.

**Describe the solution you'd like**
We would like to refactor this function, as we are processing all of our JSDoc components for each parser when we should do it once.

**Describe alternatives you've considered**
These lines https://github.com/BRIKEV/express-jsdoc-swagger/blob/master/processSwagger.js#L33 should be replaced with one method to decide which parser must be used so that we only run once all of our parse methods.

**Comment by kevinccbsg** [comment]
I created this [Branch](https://github.com/BRIKEV/express-jsdoc-swagger/tree/fix-processor) to refactor that code but as this issue was intended to fix the Memory problem that branch does not solve the problem. This is because the problem is not that code it is a glob pattern problem. We need to add an ignore option to fix this issue.

```
{ ignore: '**/node_modules/**' }
```

**Comment by davidmorabito** [comment]
Hi @kevinccbsg, 
I have an entire expressjs app template that I used as an npm module. This app has a base method for health check that all apps using this template will inherit.

I've configured my `filesPattern` with an array containing the path for the app using the template and the template itself. This endpoint in the template is not showing up in swagger due to the exclusions defined at `/consumers/globFilesMatches.js` which excludes all folders that matches `node_modules`, where sadly my template is.

Any workaround for this? Is there a way to add an "include" option or something?
Thanks!
